# Generated by Django 5.2.5 on 2025-08-14 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "chat_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("username", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        default=None,
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="botapp.chat"
                    ),
                ),
            ],
        ),
    ]
