# Generated by Django 5.2.5 on 2025-09-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="chat_id",
            new_name="id",
        ),
    ]
