# Generated by Django 5.2.5 on 2025-09-12 16:22

import botapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botapp", "0002_rename_chat_id_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="botapp.chat"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    (botapp.models.OperationType["INCOME"], "Income"),
                    (botapp.models.OperationType["EXPENSE"], "Expense"),
                ],
                default=None,
                max_length=10,
            ),
        ),
    ]
